### ISSUE TITLE
Not able to connect to the self-hosted dockerised languagetool service.

### ISSUE THREAD

**Issue by misudo** [wrenger/obsidian-languagetool#3]
I'm trying to conncet to Obsidian plugin to a local self-hosted service. It successfully bound with firefox via a https://own.local.hostmane.
Since https + domain route failed for me (separate issue created for that), I've now tried the http://ip.add.ress:1111 route, but keep getting the below message in language tool logs. 
Both obsidian docker container and languagetools share the same docker network and, judging by the logs - they can communicate, just the message format expected by the server isn't in line with what the plugin provides. 

#2024-07-30 18:50:59.865 GMT+01:00 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2024-07-30 18:50:59.869 GMT+01:00 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: **'Invalid format for 'preferredVariants', expected a dash as in 'en-GB': ''',** sending HTTP code 400. Access from 000.00.0.0, HTTP user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.7 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36, User agent param: null, Referrer: null, language: auto, h: 1, r: 219, time: 4m: ALL, l: PICKY, Stacktrace follows:org.languagetool.server.BadRequestException: Invalid format for 'preferredVariants', expected a dash as in 'en-GB': ''
        at org.languagetool.server.TextChecker.detectLanguageOfString(TextChecker.java:896)
        at org.languagetool.server.V2TextChecker.getLanguage(V2TextChecker.java:120)
        at org.languagetool.server.TextChecker.lambda$checkText$4(TextChecker.java:378)
        at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:76)
        at org.languagetool.server.TextChecker.checkText(TextChecker.java:378)
        at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:176)
        at org.languagetool.server.ApiV2.lambda$handleRequest$4(ApiV2.java:86)
        at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
        at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:86)
        at org.languagetool.server.LanguageToolHttpHandler.lambda$handle$0(LanguageToolHttpHandler.java:206)
        at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:206)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:848)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:817)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2024-07-30 18:50:59.869 GMT+01:00 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 4ms; sending code 400

The plugin spits out the following error too:
"7/30/2024, 7:03:15 PM:
Error: 'Request to LanguageTool failed: Please check your connection and server URL.
Error: Request failed, status 400'
Settings: {"serverUrl":"http://111.11.11.111:8010","autoCheckDelay":1750,"shouldAutoCheck":true,"languageVariety":{},"pickyMode":true,"synonyms":"en","staticLanguage":"en-GB","username":"REDACTED","apikey":"REDACTED"}"

Expected behaviour: the plugin connects to the local languagetool instance.
Thanks for looking into the matter.

**Comment by igrekster** [comment]
Same here, seems to be related to using the `Static Language` option, so if you select language autodetection instead, then the error goes away, but checking behaves differently compared to the original plugin: it works for checking the entire document, but not on the fly.

**Comment by wrenger** [comment]
Yes, I addressed the issue with the static language (a9534f05d960ccac64b694b87b9aa94f0e23069c)

**Comment by wrenger** [comment]
Related to #1

**Comment by igrekster** [comment]
Works great! Thank you!
